---
title: "Links"
author: "R Bootcamp 2018"
date: "September 2018"
output: 
  html_document: 
    theme: journal
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please let me know if there are other links you think should be included on this page!

# Methods links

## Download R:
 [CRAN website](https://cran.r-project.org/)  
 
## Download RStudio:   
 [Rstudio main site](https://www.rstudio.com/)     
 [R projects (useful feature of RStudio)](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects)        
 [Rstudio online learning resources](https://www.rstudio.com/online-learning/)      
 
## R Introductory Tutorials and Courses
 [Datacamp's- "Intro to R"](https://www.datacamp.com/home)   
 [Prelude in R](https://preludeinr.com)      
 [R for beginners](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf)   
 [Hadley Wickhams "R for Data Science"](http://r4ds.had.co.nz/index.html)
 [Modern Dive](https://ismayc.github.io/moderndiver-book/)     
 [Data carpentry course](http://www.datacarpentry.org/semester-biology/)
 [Many other resources](https://cran.r-project.org/other-docs.html) 
 [Many R Books (and other useful resources)](http://rbasicsworkshop.weebly.com/books.html)    
 [NCEAS tutorial- oldie but goodie](https://www.nceas.ucsb.edu/files/scicomp/Dloads/RProgramming/BestFirstRTutorial.pdf)

## R Examples (some people learn best by just playing with existing code!)            
 [R by example](http://www.mayin.org/ajayshah/KB/R/)      

## R reference cards (print 'em out and hang by your office desk!)       
 [Base R Cheat sheet](https://www.rstudio.com/wp-content/uploads/2016/05/base-r.pdf)              
 [Short Reference Card](https://cran.r-project.org/doc/contrib/Short-refcard.pdf)  
 [More comprehensive reference card](https://cran.r-project.org/doc/contrib/Baggott-refcard-v2.pdf)    
 [Data management reference card](https://sites.ualberta.ca/~ahamann/teaching/renr690/R_Cheat_Data.pdf)      
 [RStudio cheatsheets- very useful!](https://www.rstudio.com/resources/cheatsheets/)     
     Includes cheatsheets for R markdown, shiny, data wrangling with "dplyr" and much more!     

## R Markdown (for publishing and communicating in R. This website was built in R Markdown!)          
 [Guide for Pandoc Markdown](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html)   
 [Website development for RMarkdown](http://rmarkdown.rstudio.com/rmarkdown_websites.html)   
 [YAML: YAML Ain't Markup Language!](http://yaml.org/)   
 [a nice simple Markdown syntax guide](https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html)  

## GIT (for sharing your code and collaborating with others!)        
 [Excellent intro GIT tutorial](https://try.github.io/)  

## Bayesian Statistics    
 [MCMC for Dummies...](http://twiecki.github.io/blog/2015/11/10/mcmc-sampling/) (basis of MCMC lecture...)  
 [BUGS online manual](http://www.mrc-bsu.cam.ac.uk/wp-content/uploads/manual14.pdf)  
 [secret BUGS tricks](http://users.aims.ac.za/~mackay/BUGS/Manuals/Tricks.html)  
 [Approximate Bayesian Computation: overview](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002803)   
 [Bayesian Methods for Hackers!](http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/)    
 [NIMBLE (alternative implementation of BUGS language for R)](https://r-nimble.org/)  
 
## Time Series Analysis
 [A regression approach to time series analysis](http://node101.psych.cornell.edu/Darlington/series/series0.htm)  
 
## Ordination
 [Practical guide to ordination for Ecologists](http://ordination.okstate.edu/index.html)  
 
## Tree-based machine learning
 [Breiman's guide to Random Forest](http://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm)  
 [Vignette: boosted regression trees for species distribution modeling](https://cran.r-project.org/web/packages/dismo/vignettes/brt.pdf)  

## Structural Equation Modeling and Bayes Nets
 [Random but relevant blog post](http://blog.efpsa.org/2015/12/14/structural-equation-modeling-what-is-it-what-does-it-have-in-common-with-hippie-music-and-why-does-it-eat-cake-to-get-rid-of-measurement-error/)  
 ["bnlearn" package documentation for Bayes nets](http://www.bnlearn.com/)  
 
## Spatial Analysis in R
 ["raster" package vignette](https://cran.r-project.org/web/packages/raster/vignettes/Raster.pdf)   

## Spatial Capture Recapture (secr)   
 ['secr' Google Group](https://groups.google.com/forum/#!forum/secrgroup)    
 [BUGS code for secr](http://www.mikemeredith.net/blog/1309_SECR_in_JAGS_patchy_habitat.htm)
 

[Weekly math/bio "Stats chats"](https://kevintshoemaker.github.io/StatsChats/)
